### ISSUE TITLE
Mergify not working behind a proxy

### ISSUE THREAD

**Issue by jlengrand** [RamonGebben/mergify#11]
Not something you might want to fix now, but I just wanted to let you know that mergify does not work if you are behind a proxy at the moment :).
(Even with HTTP_PROXY and other variables set).

**Comment by RamonGebben** [comment]
How would I reproduce this?

**Comment by jlengrand** [comment]
This is a very good question. 

I guess by setting up a proxy :).

**Comment by jlengrand** [comment]
Alright, I just tested and this is what I get trying to access gitlab.com when behind the proxy 

```
[jlengrand@rn07t1c18:~/IdeaProjects/mergify]$ node index.js -a
⠹ Retrieving all Merge Requests assigned to you(node:73228) UnhandledPromiseRejectionWarning: FetchError: request to https://gitlab.com/api/v4//merge_requests?scope=all&assignee_id=16946 failed, reason: getaddrinfo ENOTFOUND gitlab.com gitlab.com:443
    at ClientRequest.<anonymous> (/Users/jlengrand/IdeaProjects/mergify/node_modules/node-fetch/lib/index.js:1393:11)
    at ClientRequest.emit (events.js:180:13)
    at TLSSocket.socketErrorListener (_http_client.js:395:9)
    at TLSSocket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
(node:73228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:73228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠼ Retrieving all Merge Requests assigned to you
```

I'll try to look deeper into the issue

**Comment by jlengrand** [comment]
I think it is also related, but this is what I get when I try to configure my work gitlab. I get certificate issues


```
[jlengrand@rn07t1c18:~/IdeaProjects/mergify]$ node index.js -c
? What is your Gitlab User ID? 6011
? What private token shall we use? [hidden]
? On what domain is your Gitlab instance? gitlab.company.net

🙀  Oh no, could not complete verify. Please review your config
{ FetchError: request to https://gitlab.company.net/api/v4/users/6011 failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/Users/jlengrand/IdeaProjects/mergify/node_modules/node-fetch/lib/index.js:1393:11)
    at ClientRequest.emit (events.js:180:13)
    at TLSSocket.socketErrorListener (_http_client.js:395:9)
    at TLSSocket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
  message: 'request to https://gitlab.company.net/api/v4/users/6011 failed, reason: unable to verify the first certificate',
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
```

So it looks like at the moment I can't use `mergify` at work. I'll look into that too.

**Comment by jlengrand** [comment]
Alright, so apparently @RamonGebben has all the answers, and the issue can be fixed by doing the following : 

`yarn add https-proxy-agent`

and then adding this in the `doFetch` fetchOptions : 

`agent:new HttpsProxyAgent('http://127.0.0.1:3128')`

More info can be found here : https://github.com/TooTallNate/node-https-proxy-agent.

I have to think about how to fix that in a nicer way (maybe adding a config flag)

**Comment by RamonGebben** [comment]
@jlengrand I would agree that in the config would be the best place to put it. 
You can easily extend the questions that are asked in `lib/commands/configure/inputOptions.js` these answers should be magically picked up by the config.

How ever we would need to start thinking about update paths. 

I'll open a issue for that.
